import test from 'node:test';
import assert from 'node:assert/strict';
import {buildContent,contentView,validateContent} from '../src/formatting.mjs';
const sdk=async(name,{text,formats})=>{assert.equal(name,'remnote_rich_text');return {richText:[{i:'m',text,...Object.fromEntries(formats.map(f=>[{bold:'b',italic:'l',underline:'u'}[f],true]))}]};};
test('formatted spans build selective and combined styles without parsing separators',async()=>{const r=await buildContent(sdk,{spans:[{text:'Key',formats:['bold']},{text:' → **literal** '},{text:'word',formats:['italic','underline']}]});assert.deepEqual(r,[{i:'m',text:'Key',b:true},' → **literal** ',{i:'m',text:'word',l:true,u:true}]);});
test('formatting can be removed explicitly and current unsupported nodes are retained',async()=>{const image={i:'i',url:'https://example.com/x.png'},ref={i:'q',_id:'refId'},colored={i:'m',text:'Color',h:1};const current=[{i:'m',text:'Bold',b:true},image,ref,colored];const input={spans:[{text:'Normal'},{preserve_element:1},{preserve_element:2},{preserve_element:3}]};assert.deepEqual(await buildContent(sdk,input,current),['Normal',image,ref,colored]);assert.deepEqual(contentView(current).spans.slice(1),[{preserve_element:1},{preserve_element:2},{preserve_element:3}]);});
test('dropping, duplicating, reordering or inventing protected elements is refused',async()=>{const current=['Text',{i:'i',url:'https://example.com/a.png'},{i:'q',_id:'refId'}];for(const spans of [[{text:'Flatten'}],[{preserve_element:1},{preserve_element:1},{preserve_element:2}],[{preserve_element:2},{preserve_element:1}],[{preserve_element:4}]])await assert.rejects(()=>buildContent(sdk,{spans},current));});
test('unknown styles, unknown fields, blank content and excessive spans are refused',async()=>{for(const value of [{spans:[]},{spans:[{text:'x',formats:['blink']}]},{spans:[{text:'x',formats:['bold','bold']}]},{spans:[{text:'x',url:'bad'}]},{spans:Array.from({length:101},()=>({text:'x'}))}])assert.throws(()=>validateContent(value));await assert.rejects(()=>buildContent(sdk,{spans:[{text:'   '}]}),/blank/);await assert.rejects(()=>buildContent(async()=>({richText:[{i:'i',text:'x'}]}),{spans:[{text:'x',formats:['bold']}]}),/SDK/);});
test('reader span view round trips mixed content with empty text without losing embedded data',async()=>{const current=['',{i:'m',text:'bold',b:true},' after',{i:'i',url:'https://example.com/a.png'}];const rich=await buildContent(sdk,contentView(current),current);assert.deepEqual(rich,current.slice(1));});
